- name: Allow tftp service through the firewall permanently
  ansible.posix.firewalld:
    service: 
      - tftp
      - http
    zone: public
    permanent: true
    state: enabled

- name: Reload firewalld to apply changes
  ansible.builtin.command: firewall-cmd --reload

